[project]
name = "contextlite-llamaindex"
version = "0.1.0"
description = "LlamaIndex retriever for ContextLite"
requires-python = ">=3.9"
dependencies = ["requests>=2", "llama-index-core>=0.10"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
