#!/bin/bash

echo "🔑 GitHub Secrets Configuration Guide"
echo "====================================="
echo ""
echo "Your GitHub Actions workflow needs these secrets to publish packages:"
echo ""

echo "📦 NPM Publishing:"
echo "  Secret Name: NPM_TOKEN"
echo "  How to get:"
echo "    1. Go to https://www.npmjs.com/settings/tokens"
echo "    2. Click 'Generate New Token' → 'Classic Token'"
echo "    3. Give it 'Publish' permission"
echo "    4. Copy the token"
echo "    5. Go to GitHub repo → Settings → Secrets → Actions"
echo "    6. Add secret: NPM_TOKEN = your_token_here"
echo ""

echo "🐳 Docker Hub Publishing:"
echo "  Secret Names: DOCKERHUB_USERNAME, DOCKERHUB_TOKEN"
echo "  How to get:"
echo "    1. Go to https://hub.docker.com/settings/security"
echo "    2. Click 'New Access Token'"
echo "    3. Give it 'Read, Write, Delete' permission"
echo "    4. Copy the token"
echo "    5. Go to GitHub repo → Settings → Secrets → Actions"
echo "    6. Add secrets:"
echo "       DOCKERHUB_USERNAME = michaelakuykendall"
echo "       DOCKERHUB_TOKEN = your_token_here"
echo ""

echo "✅ Already Working:"
echo "  ✓ PYPI_TOKEN - PyPI publishing"
echo "  ✓ GITHUB_TOKEN - GitHub releases"
echo ""

echo "🔗 Quick Links:"
echo "  • NPM Tokens: https://www.npmjs.com/settings/tokens"
echo "  • Docker Hub Tokens: https://hub.docker.com/settings/security"
echo "  • GitHub Repo Secrets: https://github.com/Michael-A-Kuykendall/contextlite/settings/secrets/actions"
echo "  • GitHub Actions Status: https://github.com/Michael-A-Kuykendall/contextlite/actions"
echo ""

echo "⚡ After adding secrets:"
echo "  • GitHub Actions will automatically retry failed jobs"
echo "  • OR create a new tag: git tag v1.0.6 && git push --tags"
echo "  • OR manually trigger: gh workflow run publish-packages.yml"
