# ContextLite Default Configuration
server:
  port: 8082
  host: "127.0.0.1"
  cors_enabled: false
  auth_token: "contextlite-dev-token-2025"  # Default token for development
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst: 10
    endpoint_specific:
      "/api/v1/query": 30
      "/api/v1/enterprise": 100
  
storage:
  database_path: "./contextlite_fresh.db"
  cache_size_mb: 64
  
optimization:
  solver_timeout_ms: 250
  max_opt_gap: 0.05
  max_candidates: 200
  max_pairs_per_doc: 5
  integer_scaling: 10000
  objective_style: "weighted-sum"
  z3:
    binary_path: "C:\\ProgramData\\chocolatey\\bin\\z3.exe"  # Path to optimizer binary
    enable_verification: true                                # Enable brute-force verification for small problems
    max_verification_docs: 12                                # Maximum docs for verification
  
# 7D Feature Weights (per-workspace adaptive)
weights:
  relevance: 0.30
  recency: 0.20
  entanglement: 0.15
  prior: 0.15
  authority: 0.10
  specificity: 0.05
  uncertainty: 0.05
  redundancy_penalty: 0.3
  coherence_bonus: 0.2
  weight_update_rate: 0.01
  weight_caps: [0.01, 0.5]

# Lexicographic tier multipliers (computed at runtime from bounds)
lexicographic:
  compute_at_runtime: true
  
# Îµ-budget thresholds (when objective_style = "epsilon-budget")
epsilon_budget:
  max_redundancy: 0.4
  min_coherence: 0.3
  min_recency: 0.2
  
tokenizer:
  model_id: "gpt-4"
  max_tokens_default: 4000
  
cache:
  l1_size: 1000
  l2_ttl_minutes: 30
  l3_enabled: true
  
logging:
  level: "debug"
  include_timings: true
  include_optimization_metrics: true

# Clustering and multi-workspace configuration
cluster:
  enabled: false              # Set to true to enable clustering features
  node_id: ""                 # Auto-generated if not specified
  
  discovery:
    method: "static"          # "static", "consul", "etcd", "k8s"
    endpoints: []             # Discovery service endpoints
    service_name: "contextlite"
    ttl_seconds: 30
    tags: ["local-dev"]
    
  affinity:
    workspace_routing: false  # Enable workspace-specific routing
    sticky_sessions: false    # Pin sessions to same node
    default_tier: "medium"    # Default resource tier
    rules: {}                 # Workspace-specific affinity rules
    
  load_balancing:
    strategy: "round_robin"   # "round_robin", "least_connections", "resource_based", "workspace_hash"
    health_check_interval: 30 # seconds
    unhealthy_threshold: 3
    healthy_threshold: 2
    max_load_factor: 0.85
    enable_circuit_breaker: false
    
  resource_limits: {}         # Per-workspace resource limits
  
  health_check:
    interval: 15              # seconds between health checks
    timeout: 5                # health check timeout
    unhealthy_threshold: 3
    healthy_threshold: 2
    endpoint: "/health/cluster"
