name: GoReleaser - Release Everywhere

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.1.20)'
        required: true
        type: string

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Docker Login (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Snapcraft
        if: env.SNAPCRAFT_STORE_CREDENTIALS != ''
        run: |
          sudo snap install snapcraft --classic
          # Export credentials using environment variable (new method)
          export SNAPCRAFT_STORE_CREDENTIALS="${{ secrets.SNAPCRAFT_TOKEN }}"
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

      - name: Import GPG key for AUR
        if: env.AUR_KEY != ''
        run: |
          echo "${{ secrets.AUR_KEY }}" | gpg --batch --import
        env:
          AUR_KEY: ${{ secrets.AUR_KEY }}

      - name: Setup SSH for AUR
        if: env.AUR_KEY != ''
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_KEY }}" > ~/.ssh/aur
          chmod 600 ~/.ssh/aur
          echo "Host aur.archlinux.org" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/aur" >> ~/.ssh/config
          echo "  User aur" >> ~/.ssh/config
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
        env:
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
