name: Publish NPM Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.6)'
        required: true
        type: string

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Copy npm package
        run: |
          cp -r npm-wrapper npm-package

      - name: Copy LICENSE
        run: |
          cp LICENSE npm-package/

      - name: Update package version
        run: |
          cd npm-package
          npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Install dependencies
        run: |
          cd npm-package
          npm install

      - name: Build package
        run: |
          cd npm-package
          npm run build

      - name: Test package
        run: |
          cd npm-package
          npm pack --dry-run

      - name: Publish to npm
        run: |
          cd npm-package
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
