name: Simple Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run Core Tests
        run: |
          go test ./cmd/... ./internal/... ./pkg/...
          
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Get version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Build All Platforms
        run: |
          # Create build directory
          mkdir -p build
          
          # Build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=${{ steps.version.outputs.version }}" -o build/contextlite-linux-amd64 ./cmd/contextlite/main.go
          GOOS=windows GOARCH=amd64 go build -ldflags="-X main.version=${{ steps.version.outputs.version }}" -o build/contextlite-windows-amd64.exe ./cmd/contextlite/main.go  
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.version=${{ steps.version.outputs.version }}" -o build/contextlite-darwin-amd64 ./cmd/contextlite/main.go
          GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.version=${{ steps.version.outputs.version }}" -o build/contextlite-darwin-arm64 ./cmd/contextlite/main.go
          
          # Create archives
          cd build
          zip contextlite-windows-amd64.zip contextlite-windows-amd64.exe README.md
          tar -czf contextlite-linux-amd64.tar.gz contextlite-linux-amd64 README.md
          tar -czf contextlite-darwin-amd64.tar.gz contextlite-darwin-amd64 README.md  
          tar -czf contextlite-darwin-arm64.tar.gz contextlite-darwin-arm64 README.md
          
          # Copy README for archives
          cp ../README.md .
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/contextlite-*.zip
            build/contextlite-*.tar.gz
          body: |
            ## 🚀 ContextLite ${{ steps.version.outputs.version }}
            
            ### ✨ What's New
            - 14-day full-featured trial (no registration required)
            - Professional-grade features during trial
            - Robust BM25 engine always available
            - Cross-platform support
            
            ### 📦 Quick Start
            1. Download the binary for your platform below
            2. Extract the archive  
            3. Run `./contextlite --help`
            4. Start server: `./contextlite`
            5. Visit: http://localhost:8082/health
            
            ### 🎯 Trial System
            - **Duration**: 14 days from first run
            - **Features**: All professional features included
            - **After Trial**: Purchase license at https://contextlite.com/purchase
            
            Download your platform below ⬇️
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
